/**
 * Exporters — turn a generated sheet into a Markdown character bible
 * or a JSON schema, and trigger browser downloads.
 */

import type { CharacterSheet } from "./types";

export function sheetToMarkdown(sheet: CharacterSheet): string {
  const { visual, bible } = sheet;
  const lines: string[] = [
    `# ${bible.bio.name} — Character Bible`,
    "",
    `> ${bible.bio.title} · ${bible.bio.species} · Generated by AI Character Studio`,
    "",
    `**Prompt:** ${sheet.prompt}`,
    "",
    "## Part A — Visual Generation Parameters",
    "",
    `**Art style:** ${visual.artStyle}`,
    `**Lighting:** ${visual.lighting}`,
    "",
    "### Orthographic Turnarounds",
    ...visual.turnarounds.map((t) => `- ${t}`),
    "",
    "### Facial Expressions",
    ...visual.expressions.map((e) => `- **${e.emotion}** — ${e.note}`),
    "",
    "### Action Poses",
    ...visual.actionPoses.map((p) => `- ${p}`),
    "",
    "### Callouts & Details",
    ...visual.callouts.map((c) => `- ${c}`),
    "",
    "## Part B — Character Bible",
    "",
    "### Bio",
    `- **Name:** ${bible.bio.name}`,
    `- **Age/Era:** ${bible.bio.ageEra}`,
    `- **Occupation/Role:** ${bible.bio.occupation}`,
    "",
    bible.bio.backstory,
    "",
    "### Personality Matrix",
    `- **Core traits:** ${bible.personality.coreTraits.join(", ")}`,
    `- **Motto:** "${bible.personality.motto}"`,
    "",
    "**Strengths**",
    ...bible.personality.strengths.map((s) => `- ${s}`),
    "",
    "**Weaknesses**",
    ...bible.personality.weaknesses.map((w) => `- ${w}`),
    "",
    "**Stats**",
    ...bible.personality.stats.map((s) => `- ${s.label}: ${s.value}/100`),
    "",
    "### Design Notes & Materials",
    "**Textures**",
    ...bible.design.textures.map((t) => `- ${t}`),
    "",
    `**Scale/Proportions:** ${bible.design.proportions}`,
    "",
    "**Key features**",
    ...bible.design.keyFeatures.map((f) => `- ${f}`),
    "",
    "**Color palette**",
    ...bible.design.palette.map((p) => `- ${p.name}: \`${p.hex.toUpperCase()}\``),
    "",
    "### Animation Guidelines",
    `- **Movement style:** ${bible.animation.movementStyle}`,
    `- **Gait:** ${bible.animation.gait}`,
    `- **Expression notes:** ${bible.animation.expressionNotes}`,
    "",
  ];
  if (sheet.sketchAnalysis) {
    lines.push(
      "### Sketch Analysis",
      `- **Silhouette:** ${sheet.sketchAnalysis.silhouette}`,
      `- **Stance:** ${sheet.sketchAnalysis.stance}`,
      `- **Proportions:** ${sheet.sketchAnalysis.proportions}`,
      `- **Archetypes:** ${sheet.sketchAnalysis.archetypes.join(", ")}`,
      "",
    );
  }
  return lines.join("\n");
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "character";
}

export function downloadText(filename: string, text: string, mime = "text/plain"): void {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(sheet: CharacterSheet): void {
  downloadText(`${slug(sheet.bible.bio.name)}-bible.md`, sheetToMarkdown(sheet), "text/markdown");
}

export function downloadDataUrl(filename: string, dataUrl: string): void {
  const a = document.createElement("a");
  a.href = dataUrl;
  a.download = filename;
  a.click();
}

export function sheetFileName(sheet: CharacterSheet, ext: string): string {
  return `${slug(sheet.bible.bio.name)}-sheet.${ext}`;
}
